//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf_Pharmacie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int id_produit { get; set; }
        public Nullable<int> id_stock { get; set; }
        public string nom_produit { get; set; }
        public Nullable<decimal> prix_unite { get; set; }
        public Nullable<int> quantite { get; set; }
        public string date_heure_ajout_produit { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
